In [1]:
import pandas as pd

from context import community_module
from community_module.community_detection.similarityCommunityDetection import SimilarityCommunityDetection
from community_module.similarity.emotionSimilarity import EmotionSimilarity

In [15]:
# Paso 1, Cargamos los datos
users_mncn = pd.read_csv('../../data/MNCN/user_profiles.csv')
users = users_mncn.iloc[:,1:-4]

In [16]:
users

,q103_0,q103_1,q103_2,q103_3,q103_4,q103_5,q107a_0,q107a_1,q107a_2,q107a_3,...,q107b_1,q107b_2,q110a_0,q110a_1,q110b_0,q110b_1,q110b_2,q110b_3,q110b_4,q110b_5
0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
57,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
58,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
59,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [17]:
# Paso 2, Detectamos comunidades
community_detection = SimilarityCommunityDetection(users)
result = community_detection.calculate_communities(metric='cosine', n_clusters=4)

In [18]:
# Agrego los grupos a los usuarios
users_mncn['group'] = result.values()

In [19]:
users_mncn.head()

,UserId,q103_0,q103_1,q103_2,q103_3,q103_4,q103_5,q107a_0,q107a_1,q107a_2,...,q110b_1,q110b_2,q110b_3,q110b_4,q110b_5,School,Grade,Type,Zone,group
0,3bcd671c-771d-49f3-a753-f8e5c8d2c00a,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,Colegio Arcangel,5 - Primaria,Privado,Extrarradio,0
1,b836965f-0f1f-4e60-9adf-63f7d9ced35b,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,Colegio Arcangel,5 - Primaria,Privado,Extrarradio,1
2,6753a984-128e-489e-9d49-c5406ccef6e6,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,Colegio Arcangel,5 - Primaria,Privado,Extrarradio,1
3,3fee2686-e5f9-481a-8cc3-5add84863429,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,Colegio Arcangel,5 - Primaria,Privado,Extrarradio,1
4,bc21b0cf-28d0-4bf8-8c44-a3f55ac331ef,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,Colegio Arcangel,5 - Primaria,Privado,Extrarradio,1

In [ ]:
full_data = pd.read_csv('../../data/MNCN/semana_ciencia_2021.csv')
user_desc = full_data[['UserId', 'School', 'Grade', 'Type', 'Zone']]

In [ ]:
users_mncn.join(user_desc)

In [ ]:
# Busco relación entre usu del mismo grupo
answers_q103 = users_mncn.groupby('group').sum().iloc[:, 0:6].values
answers_q107a = users_mncn.groupby('group').sum().iloc[:, 6:12].values
answers_q107b = users_mncn.groupby('group').sum().iloc[:, 12:15].values
answers_q110a = users_mncn.groupby('group').sum().iloc[:, 15:17].values
answers_q110b = users_mncn.groupby('group').sum().iloc[:, 17:].values

In [ ]:
users_mncn.groupby('group').sum().iloc[:, 0:6]

In [ ]:
users_mncn.groupby('group').sum().iloc[:, 6:12]

In [ ]:
users_mncn.groupby('group').sum().iloc[:, 12:15]

In [ ]:
users_mncn.groupby('group').sum().iloc[:, 15:17]

In [ ]:
users_mncn.groupby('group').sum().iloc[:, 17:]

In [ ]:
users_mncn.groupby('group').count().iloc[:,0]

In [ ]:
users_mncn.columns

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
labels = users_mncn.columns[1:7]
Y = answers_q103

In [ ]:
'''
width_bar = 0.2
X = np.arange(len(labels))

fig, ax = plt.subplots()


bar1 = plt.bar(X, Y[0], width_bar, align='center')
bar2 = plt.bar(X + width_bar, Y[1], width_bar, align='center')
bar3 = plt.bar(X + width_bar * 2, Y[2], width_bar, align='center')
bar4 = plt.bar(X + width_bar * 3, Y[3], width_bar, align='center')
bar5 = plt.bar(X + width_bar * 4, Y[4], width_bar, align='center')

plt.xlabel('Options')
plt.ylabel('# Answers')
plt.title('Answers to Question 103')

plt.xticks(X + width_bar, labels)
plt.legend((bar1, bar2, bar3, bar4, bar5), ('Group 1', 'Group 2', 'Group 3', 'Group 4', 'Group 5'))
fig.show()
'''

In [ ]:
len(users_mncn)